name = "m4vx-extractor-images"
main = "workers/extractor-images.ts"
compatibility_date = "2026-05-30"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/10 * * * *"]

[vars]
EXTRACTOR_SECRET = "pigga"
